{
  "formatVersion": "1.1",
  "component": {
    "group": "me.didit",
    "module": "didit-sdk-nfc",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-nfc-4.1.0.aar",
          "url": "didit-sdk-nfc-4.1.0.aar",
          "size": 179191,
          "sha512": "28f05a5c03c57df5dd8153af5e576e7c86e81f41652e897ff020d99fe1c8b72ebf60b93757dcd9360e26a73fbac56a6ec66c12b3bdc2c2706b9e1f0181bd8d1c",
          "sha256": "5645da287197fd5ce42f25cc57b1888facbd74a8a308a512d46831ca7b8a5fbf",
          "sha1": "5a57529f55be39e239c98c8f8b28192c5f2875a9",
          "md5": "5bc12225a6b56ab6e47f726a32f25b4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.80"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-nfc-4.1.0.aar",
          "url": "didit-sdk-nfc-4.1.0.aar",
          "size": 179191,
          "sha512": "28f05a5c03c57df5dd8153af5e576e7c86e81f41652e897ff020d99fe1c8b72ebf60b93757dcd9360e26a73fbac56a6ec66c12b3bdc2c2706b9e1f0181bd8d1c",
          "sha256": "5645da287197fd5ce42f25cc57b1888facbd74a8a308a512d46831ca7b8a5fbf",
          "sha1": "5a57529f55be39e239c98c8f8b28192c5f2875a9",
          "md5": "5bc12225a6b56ab6e47f726a32f25b4f"
        }
      ]
    }
  ]
}
