{
  "formatVersion": "1.1",
  "component": {
    "group": "me.didit",
    "module": "didit-sdk-wallet",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-wallet-4.7.2.aar",
          "url": "didit-sdk-wallet-4.7.2.aar",
          "size": 305810,
          "sha512": "a52f1dbb35bef7014217fd5d3d98b32dbe6dc65d0952e3a376dc567153740a5aeb646d2694ef765ba38c72c196430b4e48b41147291c49a3c8a08679cb4c6c3b",
          "sha256": "1863bc524c31f502bd439297c8dbeee79ee28f7eefee049808a907df22cf32a4",
          "sha1": "1ee593ca0a12de5ea4d7f14a150b90dae34059fc",
          "md5": "f2af640cd30f313378e672497e7b5162"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.reown",
          "module": "android-bom",
          "version": {
            "requires": "1.4.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.reown",
          "module": "android-core"
        },
        {
          "group": "com.reown",
          "module": "appkit"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-navigation-material",
          "version": {
            "requires": "0.34.0"
          }
        },
        {
          "group": "me.didit",
          "module": "didit-sdk-core",
          "version": {
            "requires": "4.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "didit-sdk-wallet-4.7.2.aar",
          "url": "didit-sdk-wallet-4.7.2.aar",
          "size": 305810,
          "sha512": "a52f1dbb35bef7014217fd5d3d98b32dbe6dc65d0952e3a376dc567153740a5aeb646d2694ef765ba38c72c196430b4e48b41147291c49a3c8a08679cb4c6c3b",
          "sha256": "1863bc524c31f502bd439297c8dbeee79ee28f7eefee049808a907df22cf32a4",
          "sha1": "1ee593ca0a12de5ea4d7f14a150b90dae34059fc",
          "md5": "f2af640cd30f313378e672497e7b5162"
        }
      ]
    }
  ]
}
